### ISSUE TITLE
[PROPOSAL] Add HOTFIX as one of the approved commit messages

### ISSUE THREAD

**Issue by ryanjwessel** [ahmadawais/Emoji-Log#10]
In a perfect world, we wouldn't need to add this. However, with client-facing software inevitably something is broken and needs to be fixed right away. Having a hotfix commit standard effectively conveys the urgency behind the commit, and provides better insight into the number of hotfixes that have been necessary throughout the history of a project. The current "fix" commit message is better-suited for non-critical issues.

I propose that we add one approved commit message in the following format:
```🔥HOTFIX: IMPERATIVE_MESSAGE_GOES_HERE```

With the following added shortcut:
```
# HOTFIX.
hot = "!f() { git cap \"🔥 HOTFIX: $@\"; }; f"
```

I'd be happy to discuss the merits of this in further detail, and I can open a PR for this if you think this is worth adding to the project!

**Comment by ahmadawais** [comment]
Thank you for taking time out to write all that. 

I believe your suggestion goes against the philosophy of this project. I want to keep the categories to a minimum. You can always subcategorize as I do in large projects. E.g. it could be:

```sh
🐛 FIX: (hotfix) Much needed SSL upgrade
🐛 FIX: (🔥) Much needed SSL upgrade
```

Adding another category is a major decision.

Thanks a lot anyways 👍

**Comment by ryanjwessel** [comment]
No problem, thanks for taking the time to consider this!

**Comment by ahmadawais** [comment]
@rynjwssl thanks for your feedback. I do really appreciate it. Looking forward to your submissions for repos that use Emoji log. :)
