### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by meyercm** [ahmadawais/Emoji-Log#12]
Looks like a copy-paste mistake between `Release` and `Test`

1. `🚀 RELEASE: IMPERATIVE_MESSAGE_GOES_HERE`
    > Use when you release a new version.
    > E.g. `🚀 RELEASE: Version 2.0.0`

1. `✅ TEST: IMPERATIVE_MESSAGE_GOES_HERE`
    > Use when you release a new version. <= Should maybe be 'Use when you update test suite'
    > E.g. `✅ TEST: Mock User Login/Logout`

**Comment by ahmadawais** [comment]
Send in a PR :)
