### ISSUE TITLE
Unable to configure that on Windows 10

### ISSUE THREAD

**Issue by Rizwanjamal** [ahmadawais/Emoji-Log#19]
I tried to use that approach by modified my git global config, but nothing seems to be working 
![image](https://user-images.githubusercontent.com/8683960/66155759-c5595080-e639-11e9-8c00-7367f4336d49.png)

**Comment by Rizwanjamal** [comment]
@ahmadawais Can you please help me how to configure that & use it ?
Thanks !

**Comment by ahmadawais** [comment]
I'm super interested in helping you work this out. For me to do that, you have to help understand each step you took. What command you ran how you ran it what error you saw. "Nothing's working" is not helpful information.

**Comment by Rizwanjamal** [comment]
@ahmadawais Can you please guide me what's the setup process. I just tried by adding the above snippet in my git global config & on using that command git new getting this information...
![image](https://user-images.githubusercontent.com/8683960/66158077-92fe2200-e63e-11e9-8d7d-6a1eb3be5298.png)

I tried to use it in many ways under *git commit -m* command and then tried the commands directly as you can see in the above screenshot. How can I configure it correctly to use it in commit messages ?

**Comment by ahmadawais** [comment]
I don't have windows so I can't test this but have you tried restarting and reloading the terminal? Looks like your git aliases were not registered.

I recommend using the .bashrc workflow functions

```sh
#.# Better Git Logs.
### Using EMOJI-LOG (https://github.com/ahmadawais/Emoji-Log).

# Git Commit, Add all and Push — in one step.
function gcap() {
    git add . && git commit -m "$*" && git push
}

# NEW.
function gnew() {
    gcap "📦 NEW: $@"
}

# IMPROVE.
function gimp() {
    gcap "👌 IMPROVE: $@"
}

# FIX.
function gfix() {
    gcap "🐛 FIX: $@"
}

# RELEASE.
function grlz() {
    gcap "🚀 RELEASE: $@"
}

# DOC.
function gdoc() {
    gcap "📖 DOC: $@"
}

# TEST.
function gtst() {
    gcap "✅ TEST: $@"
}```

**Comment by Rizwanjamal** [comment]
@ahmadawais I solved this issue & found something, when we are using command *git config --global --edit* for editing the config file then on the vim type editor when we copy the snippet so instead of placing the correct image, it's placing the some garbage type values as you can see in the below image
![image](https://user-images.githubusercontent.com/8683960/66204154-9f788e00-e6c3-11e9-8753-181eeb619875.png)..
After saving the changes, when I tried the command so it returned the correct message but the image wasn't showing, the same type of pattern `~_~` pattern was appearing on vscode logs as stored ...

So, correct approach is to edit config file by the command *notepad C:/Users/{name}/.gitconfig*, it will open your notepad so that you can easily paste the commands with having image in the right format.

Now, it's working perfect !
![image](https://user-images.githubusercontent.com/8683960/66204612-aa7fee00-e6c4-11e9-9304-83b80f410ca2.png)

What if I just modify the docs with this information through a PR ... :)

**Comment by ahmadawais** [comment]
Feel free to send in a PR. Does look like a Windows problem but maybe it's not. 
Looking forward, peace! ✌️
