### ISSUE TITLE
[REQUEST] add a WIP commit emoji

### ISSUE THREAD

**Issue by ahmad-reza619** [ahmadawais/Emoji-Log#22]
It would be good if we can use commit message that symbolize intermediate work of a things.
example: 📘WIP: (commit message goes here)

**Comment by ahmadawais** [comment]
I don't want to complicate this project. Emoji log is matured and not looking to add more log types to it. Almost everything you want to put in WIP is already covered by NEW or IMPROVE. The philosophy is to keep it simple and manageable. WIP doesn't help at all.
