### ISSUE TITLE
Initial Commit Emoji

### ISSUE THREAD

**Issue by lzlrd** [ahmadawais/Emoji-Log#28]
According to this repo, you used a flame emoji (🔥) for this purpose. Why not add `ini = "!f() { git cap \"🔥\"; }; f"` for completeness?

**Comment by ahmadawais** [comment]
Against the philosophy of this project. Also, it was an old automatic repo creation script that did that. Never amended that commit.

**Comment by lzlrd** [comment]
@ahmadawais, what do you then suggest for initial commits?

**Comment by ahmadawais** [comment]
`gnew` since it's something new.

**Comment by TechWiz-3** [comment]
Although it is against the the philosophy of the project, if you want a special label, you can use the 🎉 emoji

**Comment by ahmadawais** [comment]
Feel free to use more emoji in the commit message but probably never do that at the beginning. 🥳
