### ISSUE TITLE
Custom Workflow for .gitconfig users

### ISSUE THREAD

**Issue by juandc** [ahmadawais/Emoji-Log#8]
Some developers (like me :grimacing:) separate GIT aliases from the rest of alias in the `~/.zshrc` file, I think it would be nice to include an special workflow for`~/.gitconfig`.

This is may way:

```bash
#.# Better Git Logs.
### Using EMOJI-LOG (https://github.com/ahmadawais/Emoji-Log).

# Git Commit, Add all, and Push — in one step.
cap = "!f() { git add .; git commit -m \"$@\"; git push; }; f"

# NEW.
new = "!f() { git cap \"📦 NEW: $@\"; }; f"
# IMPROVE.
imp = "!f() { git cap \"👌 IMPROVE: $@\"; }; f"
# FIX.
fix = "!f() { git cap \"🐛 FIX: $@\"; }; f"
# RELEASE.
rlz = "!f() { git cap \"🚀 RELEASE: $@\"; }; f"
# DOC.
doc = "!f() { git cap \"📖 DOC: $@\"; }; f"
# TEST.
tst = "!f() { git cap \"✅ TEST: $@\"; }; f"
```

_Fun fact: It took me like an hour to find how to escape quotes :man_facepalming:._

What do you think?
I can create the PR :wink::+1:.

**Comment by ahmadawais** [comment]
@juandc nice. May I ask how is it different than this? https://github.com/ahmadawais/Emoji-Log#the-workflow. It gives you `git imp`, `git new` etc instead of `gimp` and `gnew`?

**Comment by juandc** [comment]
@ahmadawais Exactly. Instead of `g+cmd` aliases, this allow us to use `git + cmd`.

In my opinion, this could be just a new paragraph in [THE WORKFLOW](https://github.com/ahmadawais/Emoji-Log#the-workflow) section, something like this:

```md
### THE WORKFLOW
For quick prototyping, I have made the following functions that you can add to your .bashrc/.zshrc files and use Emoji-Log quickly.

# ... ...

To install these functions for the fish shell, run the following commands:

# ... ...

If you prefer, you can paste these aliases directly in your `~/.gitconfig` file:

# ... new commands ...
```

**Comment by ahmadawais** [comment]
Go ahead an make a PR for this. 👌
